config/routes.rb
Rails.application.routes.draw do
  resources :commitments
  resources :bank_accounts
  resources :items
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/commitment.rb
class Commitment < ApplicationRecord
    belongs_to :item
    belongs_to :bank_account
end

app/controllers/commitments_controller.rb
class CommitmentsController < ApplicationController
  before_action :set_commitment, only: %i[ show edit update destroy ]

  # GET /commitments or /commitments.json
  def index
    @commitments = Commitment.all
  end

  # GET /commitments/1 or /commitments/1.json
  def show
  end

  # GET /commitments/new
  def new
    @commitment = Commitment.new
  end

  # GET /commitments/1/edit
  def edit
  end

  # POST /commitments or /commitments.json
  def create
    @commitment = Commitment.new(commitment_params)

    respond_to do |format|
      if @commitment.save
        format.html { redirect_to commitment_url(@commitment), notice: "Commitment was successfully created." }
        format.json { render :show, status: :created, location: @commitment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @commitment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commitments/1 or /commitments/1.json
  def update
    respond_to do |format|
      if @commitment.update(commitment_params)
        format.html { redirect_to commitment_url(@commitment), notice: "Commitment was successfully updated." }
        format.json { render :show, status: :ok, location: @commitment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @commitment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commitments/1 or /commitments/1.json
  def destroy
    @commitment.destroy

    respond_to do |format|
      format.html { redirect_to commitments_url, notice: "Commitment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commitment
      @commitment = Commitment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def commitment_params
      params.require(:commitment).permit(:item_id, :bank_account_id, :value)
    end
end

app/helpers/commitments_helper.rb
module CommitmentsHelper
end

app/views/commitments/_commitment.html.erb
<div id="<%= dom_id commitment %>">
  <p>
    <strong>Item:</strong>
    <%= commitment.item_id %>
  </p>

  <p>
    <strong>Bank account:</strong>
    <%= commitment.bank_account_id %>
  </p>

  <p>
    <strong>Value:</strong>
    <%= commitment.value %>
  </p>

</div>

app/views/commitments/_form.html.erb
<%= form_with(model: commitment) do |form| %>
  <% if commitment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(commitment.errors.count, "error") %> prohibited this commitment from being saved:</h2>

      <ul>
        <% commitment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :item_id, style: "display: block" %>
    <%= form.number_field :item_id %>
  </div>

  <div>
    <%= form.label :bank_account_id, style: "display: block" %>
    <%= form.number_field :bank_account_id %>
  </div>

  <div>
    <%= form.label :value, style: "display: block" %>
    <%= form.number_field :value %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/commitments/edit.html.erb
<h1>Editing commitment</h1>

<%= render "form", commitment: @commitment %>

<br>

<div>
  <%= link_to "Show this commitment", @commitment %> |
  <%= link_to "Back to commitments", commitments_path %>
</div>

app/views/commitments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Commitments</h1>

<div id="commitments">
  <% @commitments.each do |commitment| %>
    <%= render commitment %>
    <p>
      <%= link_to "Show this commitment", commitment %>
    </p>
  <% end %>
</div>

<%= link_to "New commitment", new_commitment_path %>

app/views/commitments/new.html.erb
<h1>New commitment</h1>

<%= render "form", commitment: @commitment %>

<br>

<div>
  <%= link_to "Back to commitments", commitments_path %>
</div>

app/views/commitments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @commitment %>

<div>
  <%= link_to "Edit this commitment", edit_commitment_path(@commitment) %> |
  <%= link_to "Back to commitments", commitments_path %>

  <%= button_to "Destroy this commitment", @commitment, method: :delete %>
</div>