config/routes.rb
Rails.application.routes.draw do
  resources :commitments
  resources :bank_accounts
  resources :items
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
    belongs_to :user

    has_many :commitments
    has_many :items, through: :commitments
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  before_action :set_bank_account, only: %i[ show edit update destroy ]

  # GET /bank_accounts or /bank_accounts.json
  def index
    @bank_accounts = BankAccount.all
  end

  # GET /bank_accounts/1 or /bank_accounts/1.json
  def show
  end

  # GET /bank_accounts/new
  def new
    @bank_account = BankAccount.new
  end

  # GET /bank_accounts/1/edit
  def edit
  end

  # POST /bank_accounts or /bank_accounts.json
  def create
    @bank_account = BankAccount.new(bank_account_params)

    respond_to do |format|
      if @bank_account.save
        format.html { redirect_to bank_account_url(@bank_account), notice: "Bank account was successfully created." }
        format.json { render :show, status: :created, location: @bank_account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bank_accounts/1 or /bank_accounts/1.json
  def update
    respond_to do |format|
      if @bank_account.update(bank_account_params)
        format.html { redirect_to bank_account_url(@bank_account), notice: "Bank account was successfully updated." }
        format.json { render :show, status: :ok, location: @bank_account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bank_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bank_accounts/1 or /bank_accounts/1.json
  def destroy
    @bank_account.destroy

    respond_to do |format|
      format.html { redirect_to bank_accounts_url, notice: "Bank account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_account
      @bank_account = BankAccount.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bank_account_params
      params.require(:bank_account).permit(:display_name, :user_id, :balance)
    end
end

app/helpers/bank_accounts_helper.rb
module BankAccountsHelper
end

app/views/bank_accounts/_bank_account.html.erb
<div id="<%= dom_id bank_account %>">
  <p>
    <strong>Display name:</strong>
    <%= bank_account.display_name %>
  </p>

  <p>
    <strong>User:</strong>
    <%= bank_account.user_id %>
  </p>

  <p>
    <strong>Balance:</strong>
    <%= bank_account.balance %>
  </p>

</div>

app/views/bank_accounts/_form.html.erb
<%= form_with(model: bank_account) do |form| %>
  <% if bank_account.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bank_account.errors.count, "error") %> prohibited this bank_account from being saved:</h2>

      <ul>
        <% bank_account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :display_name, style: "display: block" %>
    <%= form.text_field :display_name %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :balance, style: "display: block" %>
    <%= form.number_field :balance %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bank_accounts/edit.html.erb
<h1>Editing bank account</h1>

<%= render "form", bank_account: @bank_account %>

<br>

<div>
  <%= link_to "Show this bank account", @bank_account %> |
  <%= link_to "Back to bank accounts", bank_accounts_path %>
</div>

app/views/bank_accounts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bank accounts</h1>

<div id="bank_accounts">
  <% @bank_accounts.each do |bank_account| %>
    <%= render bank_account %>
    <p>
      <%= link_to "Show this bank account", bank_account %>
    </p>
  <% end %>
</div>

<%= link_to "New bank account", new_bank_account_path %>

app/views/bank_accounts/new.html.erb
<h1>New bank account</h1>

<%= render "form", bank_account: @bank_account %>

<br>

<div>
  <%= link_to "Back to bank accounts", bank_accounts_path %>
</div>

app/views/bank_accounts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bank_account %>

<div>
  <%= link_to "Edit this bank account", edit_bank_account_path(@bank_account) %> |
  <%= link_to "Back to bank accounts", bank_accounts_path %>

  <%= button_to "Destroy this bank account", @bank_account, method: :delete %>
</div>